"use client";
import { FormEvent, useMemo, useState } from "react";
type Product={id:string;brand:string;name:string;duration:string;price:number;stock:number;color:string;mark:string};
const PRODUCTS:Product[]=[
{id:"yt30",brand:"YouTube",name:"YouTube Premium",duration:"30 วัน",price:69,stock:24,color:"#ff0033",mark:"▶"},{id:"nf7",brand:"Netflix",name:"Netflix Premium",duration:"7 วัน",price:49,stock:8,color:"#e50914",mark:"N"},{id:"viu30",brand:"Viu",name:"Viu Premium",duration:"30 วัน",price:29,stock:177,color:"#f4c400",mark:"V"},{id:"iq30",brand:"iQIYI",name:"iQIYI Premium",duration:"30 วัน",price:39,stock:15,color:"#18c96e",mark:"iQ"},{id:"wetv30",brand:"WeTV",name:"WeTV VIP",duration:"30 วัน",price:49,stock:12,color:"#00b7ff",mark:"W"},{id:"prime30",brand:"Prime Video",name:"Prime Video",duration:"30 วัน",price:65,stock:32,color:"#08a5e8",mark:"P"},{id:"disney30",brand:"Disney+",name:"Disney+ Hotstar",duration:"30 วัน",price:59,stock:19,color:"#6248ff",mark:"D+"},{id:"canva30",brand:"Canva",name:"Canva Pro",duration:"30 วัน",price:39,stock:9,color:"#7a44dc",mark:"C"}];
const API_URL="PASTE_YOUR_APPS_SCRIPT_WEB_APP_URL_HERE";
export default function Home(){
const[page,setPage]=useState<"home"|"products"|"history"|"deposit">("home"),[auth,setAuth]=useState<"login"|"register"|null>(null),[showPassword,setShowPassword]=useState(false),[search,setSearch]=useState(""),[cart,setCart]=useState<Product[]>([]),[toast,setToast]=useState(""),[slip,setSlip]=useState<File|null>(null),[checking,setChecking]=useState(false);
const products=useMemo(()=>PRODUCTS.filter(p=>`${p.brand} ${p.name}`.toLowerCase().includes(search.toLowerCase())),[search]);
const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(""),2600)};
async function submitSlip(e:FormEvent){e.preventDefault();if(!slip)return notify("กรุณาเลือกรูปสลิปก่อน");if(API_URL.startsWith("PASTE_"))return notify("กรุณาตั้งค่า Apps Script URL ก่อนใช้งานจริง");setChecking(true);try{const base64=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(",")[1]);r.onerror=reject;r.readAsDataURL(slip)});const response=await fetch(API_URL,{method:"POST",body:JSON.stringify({action:"deposit",token:localStorage.getItem("monty_token"),image:base64,mimeType:slip.type})});const result=await response.json();notify(result.ok?`เติมเงินสำเร็จ ฿${result.amount}`:result.message||"ตรวจสลิปไม่สำเร็จ")}catch{notify("เชื่อมต่อระบบตรวจสลิปไม่สำเร็จ")}finally{setChecking(false)}}
function addCart(p:Product){setCart(c=>[...c,p]);notify(`เพิ่ม ${p.name} ลงตะกร้าแล้ว`)}
return <main><header className="nav"><button className="brand" onClick={()=>setPage("home")}><span className="brand-mark">M</span><span>MONTY<span>STORE</span></span></button><nav>{[["home","หน้าหลัก"],["products","สินค้า"],["history","ประวัติ"],["deposit","เติมเงิน"]].map(([id,label])=><button key={id} className={page===id?"active":""} onClick={()=>setPage(id as typeof page)}>{label}</button>)}</nav><div className="nav-actions"><button className="cart" onClick={()=>notify(`มีสินค้า ${cart.length} รายการในตะกร้า`)}>🛒<b>{cart.length}</b></button><button className="login" onClick={()=>setAuth("login")}>เข้าสู่ระบบ</button></div></header>
{page==="home"&&<><section className="hero"><div><div className="eyebrow">DIGITAL PREMIUM STORE</div><h1>แอปพรีเมียมที่ใช่<br/><span>พร้อมใช้งานได้ทันที</span></h1><p>รวมบริการสตรีมมิงและเครื่องมือยอดนิยม ราคาสบายกระเป๋า ซื้อสะดวก ดูแลหลังการขาย</p><div className="hero-buttons"><button onClick={()=>setPage("products")}>เลือกดูสินค้า</button><button className="outline" onClick={()=>setPage("deposit")}>วิธีเติมเงิน</button></div><div className="trust"><span>✓ ส่งสินค้าไว</span><span>✓ ชำระเงินปลอดภัย</span><span>✓ ดูแลทุกออเดอร์</span></div></div><div className="hero-card"><div className="orb orb1"/><div className="orb orb2"/><div className="mascot">M</div><h2>MONTYSTORE</h2><p>ความบันเทิงครบ จบในที่เดียว</p><div className="mini-apps"><i>▶</i><i>N</i><i>V</i><i>iQ</i></div></div></section><section className="stats"><div><b>8+</b><span>แอปยอดนิยม</span></div><div><b>24/7</b><span>สั่งซื้อได้ทุกเวลา</span></div><div><b>100%</b><span>ตรวจสอบสถานะได้</span></div></section><ProductSection title="สินค้ายอดนิยม" products={PRODUCTS.slice(0,4)} addCart={addCart} buy={p=>notify(`เลือกซื้อ ${p.name}`)}/></>}
{page==="products"&&<section className="content"><div className="section-head"><div><span>ALL PRODUCTS</span><h2>เลือกแพ็กเกจที่ต้องการ</h2></div><input aria-label="ค้นหาสินค้า" value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหาแอป..."/></div><ProductSection products={products} addCart={addCart} buy={p=>notify(`เลือกซื้อ ${p.name}`)}/></section>}
{page==="history"&&<section className="empty-page"><div className="empty-icon">↻</div><h2>ประวัติการสั่งซื้อ</h2><p>เข้าสู่ระบบเพื่อดูรายการสั่งซื้อและสถานะสินค้า</p><button onClick={()=>setAuth("login")}>เข้าสู่ระบบ</button></section>}
{page==="deposit"&&<section className="deposit-page"><div className="deposit-title"><span>SLIP SCAN PAY</span><h2>เติมเงินด้วยสลิป</h2><p>โอนผ่าน Mobile Banking แล้วอัปโหลดสลิป ระบบจะตรวจสอบและเพิ่มเครดิตให้อัตโนมัติ</p></div><div className="deposit-grid"><div className="bank-card"><small>โอนเงินเข้าบัญชี</small><h3>ตั้งค่าธนาคารใน Apps Script</h3><div className="account">XXX-X-XXXXX-X</div><small>ชื่อบัญชี</small><strong>ตั้งค่าชื่อบัญชีของร้าน</strong><button onClick={()=>notify("กรุณาตั้งค่าเลขบัญชีจริงก่อน")}>คัดลอกเลขบัญชี</button></div><form className="upload-card" onSubmit={submitSlip}><label className="drop"><input type="file" accept="image/png,image/jpeg" onChange={e=>setSlip(e.target.files?.[0]||null)}/><span>{slip?"✓":"↑"}</span><b>{slip?slip.name:"แตะเพื่อเลือกรูปสลิป"}</b><small>รองรับ PNG และ JPEG ที่มี QR Code</small></label><div className="warning">สลิปต้องสร้างจากแอป Mobile Banking และมี QR Code เท่านั้น ไม่รองรับภาพรายการเดินบัญชีหรือสลิปจาก E-Wallet</div><button className="check" disabled={checking}>{checking?"กำลังตรวจสอบ...":"ตรวจสอบสลิปและเติมเงิน"}</button><p className="fee">ไม่มีค่าธรรมเนียม</p></form></div></section>}
{auth&&<div className="modal-backdrop" onMouseDown={()=>setAuth(null)}><section className="auth-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setAuth(null)}>×</button><div className="auth-logo">M</div><h2>{auth==="login"?"ยินดีต้อนรับกลับ":"สร้างบัญชี MONTYSTORE"}</h2><p>{auth==="login"?"เข้าสู่ระบบเพื่อเลือกซื้อสินค้า":"สมัครสมาชิกเพื่อเริ่มใช้งาน"}</p><form onSubmit={e=>{e.preventDefault();notify(auth==="login"?"ตัวอย่างหน้าเข้าสู่ระบบ":"ตัวอย่างหน้าสมัครสมาชิก")}}><label>Username<input required autoComplete="username" placeholder="กรอก Username"/></label>{auth==="register"&&<label>Gmail<input required type="email" placeholder="name@gmail.com"/></label>}<label>Password<div className="password"><input required type={showPassword?"text":"password"} autoComplete={auth==="login"?"current-password":"new-password"} placeholder="กรอกรหัสผ่าน"/><button type="button" onClick={()=>setShowPassword(v=>!v)} aria-label="แสดงหรือซ่อนรหัสผ่าน">{showPassword?"◉":"◌"}</button></div></label>{auth==="register"&&<label>ยืนยัน Password<input required type={showPassword?"text":"password"} placeholder="กรอกรหัสผ่านอีกครั้ง"/></label>}{auth==="login"&&<label className="remember"><input type="checkbox"/> จดจำอุปกรณ์นี้</label>}<button className="submit">{auth==="login"?"เข้าสู่ระบบ":"สมัครสมาชิก"}</button></form><div className="switch">{auth==="login"?"ยังไม่มีบัญชี? ":"มีบัญชีอยู่แล้ว? "}<button onClick={()=>setAuth(auth==="login"?"register":"login")}>{auth==="login"?"สมัครสมาชิก":"เข้าสู่ระบบ"}</button></div></section></div>}{toast&&<div className="toast">{toast}</div>}<footer><div className="brand foot"><span className="brand-mark">M</span><span>MONTYSTORE</span></div><p>ร้านแอปพรีเมียม ใช้ง่าย สั่งซื้อสะดวก</p><small>© 2026 MONTYSTORE</small></footer></main>}
function ProductSection({title,products,addCart,buy}:{title?:string;products:Product[];addCart:(p:Product)=>void;buy:(p:Product)=>void}){return <section className="products-wrap">{title&&<div className="section-title"><span>POPULAR PICKS</span><h2>{title}</h2></div>}<div className="products">{products.map(p=><article className="product" key={p.id}><div className="product-art" style={{background:`linear-gradient(145deg, ${p.color}, #15111f)`}}><strong>{p.mark}</strong><span>{p.duration}</span></div><small>{p.brand}</small><h3>{p.name}</h3><div className={p.stock?"stock":"stock out"}>{p.stock?`พร้อมขาย ${p.stock}`:"สินค้าหมด"}</div><b className="price">฿{p.price.toFixed(2)}</b><p>เหลือรวม {p.stock} ชิ้น</p><div className="product-actions"><button onClick={()=>buy(p)} disabled={!p.stock}>ซื้อทันที</button><button onClick={()=>addCart(p)} disabled={!p.stock}>＋ เพิ่ม</button></div></article>)}</div></section>}
