const CONFIG=Object.freeze({SHEET_ID:'PUT_GOOGLE_SHEET_ID_HERE',SLIP_API_URL:'PUT_SLIP_API_ENDPOINT_HERE',SLIP_API_TOKEN:'PUT_SLIP_API_TOKEN_HERE',RECEIVER_ACCOUNT:'PUT_STORE_ACCOUNT_NUMBER_HERE',SESSION_DAYS:30});
const TABLES={Users:['id','username','gmail','passwordHash','salt','balance','createdAt','status'],Sessions:['token','userId','deviceId','expiresAt','createdAt'],Products:['id','brand','name','duration','price','stock','active','imageUrl','createdAt','updatedAt'],Orders:['id','userId','itemsJson','total','status','createdAt'],Deposits:['id','userId','transRef','amount','sender','receiver','status','createdAt','rawJson']};
function setup(){const ss=SpreadsheetApp.openById(CONFIG.SHEET_ID);Object.entries(TABLES).forEach(([name,headers])=>{let s=ss.getSheetByName(name);if(!s)s=ss.insertSheet(name);if(!s.getLastRow())s.appendRow(headers);s.setFrozenRows(1)});return'พร้อมใช้งาน'}
function doGet(e){return respond_({ok:true,service:'MONTYSTORE API',action:e?.parameter?.action||'health'})}
function doPost(e){try{const b=JSON.parse(e.postData.contents||'{}'),actions={register:register_,login:login_,me:me_,logout:logout_,products:products_,deposit:deposit_,orders:orders_};if(!actions[b.action])throw new Error('ไม่พบคำสั่งที่ร้องขอ');return respond_(actions[b.action](b))}catch(error){return respond_({ok:false,message:error.message||'เกิดข้อผิดพลาด'})}}
function register_(b){const username=clean_(b.username).toLowerCase(),gmail=clean_(b.gmail).toLowerCase();if(!/^[a-z0-9_.-]{4,24}$/.test(username))throw new Error('Username ต้องมี 4–24 ตัวและใช้ภาษาอังกฤษหรือตัวเลข');if(!/^[^\s@]+@gmail\.com$/.test(gmail))throw new Error('กรุณาใช้ Gmail ที่ถูกต้อง');if(String(b.password||'').length<8)throw new Error('Password ต้องมีอย่างน้อย 8 ตัว');const users=rows_('Users');if(users.some(u=>u.username===username||u.gmail===gmail))throw new Error('Username หรือ Gmail นี้ถูกใช้แล้ว');const salt=Utilities.getUuid(),id='usr_'+Utilities.getUuid();append_('Users',[id,username,gmail,hash_(b.password,salt),salt,0,new Date(),'active']);return createSession_(id,b.deviceId)}
function login_(b){const username=clean_(b.username).toLowerCase(),user=rows_('Users').find(u=>u.username===username&&u.status==='active');if(!user||user.passwordHash!==hash_(b.password,user.salt))throw new Error('Username หรือ Password ไม่ถูกต้อง');return createSession_(user.id,b.deviceId)}
function createSession_(userId,deviceId){const token=Utilities.getUuid()+Utilities.getUuid(),expires=new Date(Date.now()+CONFIG.SESSION_DAYS*86400000);append_('Sessions',[hashToken_(token),userId,clean_(deviceId),expires,new Date()]);const user=rows_('Users').find(u=>u.id===userId);return{ok:true,token,user:{username:user.username,gmail:user.gmail,balance:Number(user.balance)||0},expiresAt:expires}}
function me_(b){const u=auth_(b.token);return{ok:true,user:{username:u.username,gmail:u.gmail,balance:Number(u.balance)||0}}}function logout_(b){deleteRowWhere_('Sessions','token',hashToken_(b.token));return{ok:true}}function products_(){return{ok:true,products:rows_('Products').filter(p=>String(p.active).toLowerCase()!=='false')}}function orders_(b){const u=auth_(b.token);return{ok:true,orders:rows_('Orders').filter(o=>o.userId===u.id)}}
function deposit_(b){const lock=LockService.getScriptLock();lock.waitLock(20000);try{const user=auth_(b.token);if(!b.image||!b.mimeType)throw new Error('ไม่พบรูปสลิป');const result=verifySlip_(b.image,b.mimeType),transRef=clean_(result.transRef||result.transactionId||result.reference),amount=Number(result.amount||result.transAmount),receiver=String(result.receiver?.account||result.receiverAccount||'').replace(/\D/g,'');if(!transRef||!amount||amount<=0)throw new Error('ไม่สามารถอ่านข้อมูลจากสลิปได้');if(CONFIG.RECEIVER_ACCOUNT!=='PUT_STORE_ACCOUNT_NUMBER_HERE'&&receiver&&!receiver.endsWith(CONFIG.RECEIVER_ACCOUNT.replace(/\D/g,'').slice(-4)))throw new Error('สลิปนี้ไม่ได้โอนเข้าบัญชีร้าน');if(rows_('Deposits').some(d=>d.transRef===transRef))throw new Error('สลิปนี้ถูกใช้เติมเงินแล้ว');const id='dep_'+Utilities.getUuid();append_('Deposits',[id,user.id,transRef,amount,JSON.stringify(result.sender||''),JSON.stringify(result.receiver||''),'success',new Date(),JSON.stringify(result)]);updateUserBalance_(user.id,amount);return{ok:true,amount,balance:(Number(user.balance)||0)+amount,depositId:id}}finally{lock.releaseLock()}}
function verifySlip_(image,mimeType){if(CONFIG.SLIP_API_URL.startsWith('PUT_'))throw new Error('ยังไม่ได้ตั้งค่า API ตรวจสลิป');const response=UrlFetchApp.fetch(CONFIG.SLIP_API_URL,{method:'post',contentType:'application/json',muteHttpExceptions:true,headers:{Authorization:'Bearer '+CONFIG.SLIP_API_TOKEN},payload:JSON.stringify({image,mimeType})}),data=JSON.parse(response.getContentText()||'{}');if(response.getResponseCode()>=300||data.success===false)throw new Error(data.message||'API ตรวจสลิปไม่สำเร็จ');return data.data||data}
function auth_(token){if(!token)throw new Error('กรุณาเข้าสู่ระบบ');const s=rows_('Sessions').find(x=>x.token===hashToken_(token)&&new Date(x.expiresAt).getTime()>Date.now());if(!s)throw new Error('Session หมดอายุ กรุณาเข้าสู่ระบบใหม่');const u=rows_('Users').find(x=>x.id===s.userId&&x.status==='active');if(!u)throw new Error('ไม่พบบัญชีผู้ใช้');return u}
function updateUserBalance_(id,add){const s=sheet_('Users'),v=s.getDataRange().getValues(),h=v[0],idCol=h.indexOf('id'),balanceCol=h.indexOf('balance');for(let i=1;i<v.length;i++)if(v[i][idCol]===id){s.getRange(i+1,balanceCol+1).setValue((Number(v[i][balanceCol])||0)+add);return}throw new Error('ไม่พบบัญชีผู้ใช้')}
function sheet_(n){return SpreadsheetApp.openById(CONFIG.SHEET_ID).getSheetByName(n)}function rows_(n){const v=sheet_(n).getDataRange().getValues(),h=v.shift()||[];return v.filter(r=>r.some(x=>x!=='')).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]])))}function append_(n,r){sheet_(n).appendRow(r)}function clean_(v){return String(v||'').trim()}function hash_(p,s){return Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,s+String(p),Utilities.Charset.UTF_8))}function hashToken_(t){return Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(t),Utilities.Charset.UTF_8))}function deleteRowWhere_(n,k,val){const s=sheet_(n),v=s.getDataRange().getValues(),c=v[0].indexOf(k);for(let i=v.length-1;i>0;i--)if(v[i][c]===val)s.deleteRow(i+1)}function respond_(d){return ContentService.createTextOutput(JSON.stringify(d)).setMimeType(ContentService.MimeType.JSON)}
